version: "3.8"

services:
  client:
    build:
      context: ./yul-yort
      dockerfile: Dockerfile.production
    networks:
      - yul_yort
    volumes:
      - client-build:/app/build
  admin:
    build:
      context: ./yul-yort-admin
      dockerfile: Dockerfile.production
    networks:
      - yul_yort
    volumes:
      - admin-build:/app/build
  server:
    build:
      context: ./yul-yort-back-end
      dockerfile: Dockerfile
    container_name: yul-yort-server
    restart: always
    volumes:
      - ./yul-yort-back-end/src/:/app/src
    ports:
      - "9000:9000"
    depends_on:
      - mysql_db
    networks:
      - yul_yort
  mysql_db:
    container_name: mysql_db
    image: mysql:8
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - yul_yort
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yul-yort-test
    ports:
      - "3306:3306"
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    networks:
      - yul_yort
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "5500:5500"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - client-build:/usr/share/nginx/html
      - admin-build:/usr/share/nginx/admin/html
      - ./nginx/nginx.conf:/etc/nginx/conf/conf.d/default.conf
    networks:
      - yul_yort
    depends_on:
      - client
      - admin

networks:
  yul_yort:
    driver: bridge

volumes:
  db:
  client-build:
  admin-build:
