version: "3"

services:
  client:
    restart: always
    build:
      context: ./yul-yort
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./yul-yort/src/:/app/src
    networks:
      - yul_yort
  # admin:
  #   restart: always
  #   build:
  #     context: ./yul-yort-admin
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4000:3000"
  #   volumes:
  #     - ./yul-yort-admin/src/:/app/src
  #   networks:
  #     - yul_yort
  server:
    build: ./yul-yort-back-end
    container_name: server
    restart: always
    volumes:
      - ./yul-yort-back-end/src/:/app/src
    ports:
      - "9000:9000"
    depends_on:
      - mysql_db
    networks:
      - yul_yort
  mysql_db:
    container_name: mysql_db
    image: mysql:8
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - yul_yort
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yul-yort-test
    ports:
      - "3306:3306"
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    networks:
      - yul_yort
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"

networks:
  yul_yort:
    driver: bridge

volumes:
  db:
