version: "3.8"

services:
  client:
    image: client
    container_name: client
    networks:
      - yul_yort
    volumes:
      - client-build:/app/build
  admin:
    image: admin
    container_name: admin
    networks:
      - yul_yort
    volumes:
      - admin-build:/app/build
  backend:
    image: backend
    container_name: backend
    restart: always
    hostname: backend
    volumes:
      - ./yul-yort-back-end/src/:/app/src
    ports:
      - "9000:9000"
    depends_on:
      - mysql_db
    networks:
      - yul_yort
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - yul_yort
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yul-yort-test
    ports:
      - "3306:3306"
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    hostname: phpmyadmin
    networks:
      - yul_yort
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "5500:80"
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config:/usr/share/nginx/html
      - client-build:/usr/share/nginx/html/client
      - admin-build:/usr/share/nginx/html/admin
    networks:
      - yul_yort
    depends_on:
      - client
      - backend
      - phpMyAdmin
      - admin

networks:
  yul_yort:
    driver: bridge

volumes:
  db:
  client-build:
  admin-build:
